// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file DdsConfig.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_DDSCONFIG_H_
#define _FAST_DDS_GENERATED_DDSCONFIG_H_


#include <fastrtps/utils/fixed_size_string.hpp>

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>
#include <DdsTopics/SizeTopics.h>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(DdsConfig_SOURCE)
#define DdsConfig_DllAPI __declspec( dllexport )
#else
#define DdsConfig_DllAPI __declspec( dllimport )
#endif // DdsConfig_SOURCE
#else
#define DdsConfig_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define DdsConfig_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


/*!
 * @brief This class represents the structure DdsConfig defined by the user in the IDL file.
 * @ingroup DDSCONFIG
 */
class DdsConfig
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport DdsConfig();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~DdsConfig();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object DdsConfig that will be copied.
     */
    eProsima_user_DllExport DdsConfig(
            const DdsConfig& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object DdsConfig that will be copied.
     */
    eProsima_user_DllExport DdsConfig(
            DdsConfig&& x);

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object DdsConfig that will be copied.
     */
    eProsima_user_DllExport DdsConfig& operator =(
            const DdsConfig& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object DdsConfig that will be copied.
     */
    eProsima_user_DllExport DdsConfig& operator =(
            DdsConfig&& x);

    /*!
     * @brief Comparison operator.
     * @param x DdsConfig object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const DdsConfig& x) const;

    /*!
     * @brief Comparison operator.
     * @param x DdsConfig object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const DdsConfig& x) const;

    /*!
     * @brief This function sets a value in member config_time
     * @param _config_time New value for member config_time
     */
    eProsima_user_DllExport void config_time(
            int64_t _config_time);

    /*!
     * @brief This function returns the value of member config_time
     * @return Value of member config_time
     */
    eProsima_user_DllExport int64_t config_time() const;

    /*!
     * @brief This function returns a reference to member config_time
     * @return Reference to member config_time
     */
    eProsima_user_DllExport int64_t& config_time();

    /*!
     * @brief This function sets a value in member id_source
     * @param _id_source New value for member id_source
     */
    eProsima_user_DllExport void id_source(
            uint32_t _id_source);

    /*!
     * @brief This function returns the value of member id_source
     * @return Value of member id_source
     */
    eProsima_user_DllExport uint32_t id_source() const;

    /*!
     * @brief This function returns a reference to member id_source
     * @return Reference to member id_source
     */
    eProsima_user_DllExport uint32_t& id_source();

    /*!
     * @brief This function sets a value in member id_target
     * @param _id_target New value for member id_target
     */
    eProsima_user_DllExport void id_target(
            uint32_t _id_target);

    /*!
     * @brief This function returns the value of member id_target
     * @return Value of member id_target
     */
    eProsima_user_DllExport uint32_t id_target() const;

    /*!
     * @brief This function returns a reference to member id_target
     * @return Reference to member id_target
     */
    eProsima_user_DllExport uint32_t& id_target();

    /*!
     * @brief This function copies the value in member conf_subject
     * @param _conf_subject New value to be copied in member conf_subject
     */
    eProsima_user_DllExport void conf_subject(
            const std::vector<char>& _conf_subject);

    /*!
     * @brief This function moves the value in member conf_subject
     * @param _conf_subject New value to be moved in member conf_subject
     */
    eProsima_user_DllExport void conf_subject(
            std::vector<char>&& _conf_subject);

    /*!
     * @brief This function returns a constant reference to member conf_subject
     * @return Constant reference to member conf_subject
     */
    eProsima_user_DllExport const std::vector<char>& conf_subject() const;

    /*!
     * @brief This function returns a reference to member conf_subject
     * @return Reference to member conf_subject
     */
    eProsima_user_DllExport std::vector<char>& conf_subject();

    /*!
     * @brief This function returns the maximum serialized size of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function returns the serialized size of a data depending on the buffer alignment.
     * @param data Data which is calculated its serialized size.
     * @param current_alignment Buffer alignment.
     * @return Serialized size.
     */
    eProsima_user_DllExport static size_t getCdrSerializedSize(
            const DdsConfig& data,
            size_t current_alignment = 0);


    /*!
     * @brief This function serializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serialize(
            eprosima::fastcdr::Cdr& cdr) const;

    /*!
     * @brief This function deserializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void deserialize(
            eprosima::fastcdr::Cdr& cdr);



    /*!
     * @brief This function returns the maximum serialized size of the Key of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function tells you if the Key has been defined for this type
     */
    eProsima_user_DllExport static bool isKeyDefined();

    /*!
     * @brief This function serializes the key members of an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serializeKey(
            eprosima::fastcdr::Cdr& cdr) const;

private:

    int64_t m_config_time;
    uint32_t m_id_source;
    uint32_t m_id_target;
    std::vector<char> m_conf_subject;
};

#endif // _FAST_DDS_GENERATED_DDSCONFIG_H_